english.telegram.bot:
  userName: ${USER_NAME}
  botToken: ${BOT_TOKEN}

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin
    schema: schema.sql
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

