english.telegram.bot:
  userName: ${USER_NAME}
  botToken: ${BOT_TOKEN}
  translatorHost: "wordsapiv1.p.rapidapi.com"
  authKey: ${RAPID_API_AUTH_KEY}

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin
    schema: schema.sql
  jpa:
    hibernate:
      ddl-auto: create-drop #TODO: don't forget change to create or none
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

